In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlflow import sklearn
%matplotlib inline

In [2]:
df = pd.read_csv("6-bank_customers.csv")

In [3]:
df.head()

age  job_satisfaction   balance  duration_last_call  \
0 -0.377957          1.043895  1.043494           -0.101838   
1 -0.325259          1.276263 -0.686123           -2.463205   
2  0.739019         -0.600903 -0.177294            1.335714   
3  0.474312         -1.103002  1.189936           -0.800186   
4  0.927365          1.114796  0.080284            1.261064   

   num_contacts_last_month  has_housing_loan  has_personal_loan  \
0                -1.617442          0.402713           0.913601   
1                -0.489426         -0.240715          -1.469496   
2                -0.817332         -0.790047           1.457365   
3                 0.912377         -0.406451          -1.130950   
4                 0.761179          0.921563           0.440832   

   communication_type  days_since_last_contact  campaign_response_score  \
0           -0.067192                 0.175471                -1.049646   
1            1.006633                -0.833692                 0.957744   
2           -0.218981                 0.878643                -1.257740   
3            1.985111                 1.379029                 1.041768   
4            0.184645                -1.567739                -0.142107   

   subscribed  
0           0  
1           0  
2           0  
3           1  
4           1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [5]:
df.columns

Index(['age', 'job_satisfaction', 'balance', 'duration_last_call',
       'num_contacts_last_month', 'has_housing_loan', 'has_personal_loan',
       'communication_type', 'days_since_last_contact',
       'campaign_response_score', 'subscribed'],
      dtype='object')

In [6]:
df.describe()

age  job_satisfaction      balance  duration_last_call  \
count  1000.000000       1000.000000  1000.000000         1000.000000   
mean     -0.015084          0.031559     0.045069           -0.020771   
std       1.021848          1.004281     1.006910            1.392738   
min      -3.718638         -3.116027    -3.534257           -4.999018   
25%      -0.685005         -0.657545    -0.647051           -1.057938   
50%      -0.030546          0.045869     0.040586            0.204506   
75%       0.662124          0.701601     0.731615            1.061181   
max       2.765266          2.658705     3.357941            3.477210   

       num_contacts_last_month  has_housing_loan  has_personal_loan  \
count              1000.000000       1000.000000        1000.000000   
mean                  0.016769         -0.042135          -0.025139   
std                   1.268761          1.029279           1.267490   
min                  -2.587178         -3.250031          -4.932878   
25%                  -0.981320         -0.722970          -0.855392   
50%                  -0.317137         -0.022343           0.148199   
75%                   1.017388          0.596557           1.020255   
max                   3.954873          3.206344           2.343380   

       communication_type  days_since_last_contact  campaign_response_score  \
count         1000.000000              1000.000000              1000.000000   
mean             0.058969                -0.015637                 0.022327   
std              0.992629                 1.000664                 1.135131   
min             -3.187779                -2.819987                -2.071129   
25%             -0.598669                -0.693330                -1.050201   
50%              0.052208                 0.018807                -0.037530   
75%              0.722446                 0.641338                 0.760782   
max              3.600187                 3.477044                 4.124285   

        subscribed  
count  1000.000000  
mean      0.503000  
std       0.500241  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [7]:
df.isna().sum()

age                        0
job_satisfaction           0
balance                    0
duration_last_call         0
num_contacts_last_month    0
has_housing_loan           0
has_personal_loan          0
communication_type         0
days_since_last_contact    0
campaign_response_score    0
subscribed                 0
dtype: int64

In [8]:
X = df.drop("subscribed", axis=1)
y = df["subscribed"]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)

LogisticRegression()

In [12]:
y_pred = logistic.predict(X_test)

In [13]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1])

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [15]:
score = accuracy_score(y_pred, y_test)
print("score= ",score)
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

score=  0.925
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       100
           1       0.92      0.93      0.93       100

    accuracy                           0.93       200
   macro avg       0.93      0.93      0.92       200
weighted avg       0.93      0.93      0.92       200

[[92  8]
 [ 7 93]]


In [16]:
#hyperparameter tuning

In [17]:
model = LogisticRegression()

In [18]:
penalty = ["l1","l2","elasticnet"]
c_values = [100, 10, 1, 0.1, 0.01] # cezalandırma katsayısı gibi bir ley
solver = ["newton_cg","lbfgs","liblinear","sag","saga","newton-cholesky"]

In [19]:
params = dict(penalty=penalty, C=c_values, solver=solver)

In [20]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['newton_cg',
  'lbfgs',
  'liblinear',
  'sag',
  'saga',
  'newton-cholesky']}

In [21]:
#grid search cv

In [22]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [23]:
cv = StratifiedKFold()

In [24]:
grid = GridSearchCV(estimator=model, param_grid=params, cv=cv,scoring="accuracy", n_jobs=-1)

In [25]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton_cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [26]:
grid.fit(X_train, y_train)

C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
275 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton_cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [27]:
grid.best_params_ #yukarıdaki sözlükten denedi ve en uygun parametreleri çıkardı.

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [28]:
grid.best_score_

np.float64(0.925)

In [29]:
y_pred = grid.predict(X_test)

In [30]:
score = accuracy_score(y_pred, y_test)
print("score= ",score)
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

score=  0.935
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       104
           1       0.91      0.96      0.93        96

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.93       200
weighted avg       0.94      0.94      0.94       200

[[95  9]
 [ 4 92]]


In [32]:
y_pred = grid.predict(X_test)

In [33]:
score = accuracy_score(y_pred, y_test)
print("score= ",score)
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

score=  0.935
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       104
           1       0.91      0.96      0.93        96

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.93       200
weighted avg       0.94      0.94      0.94       200

[[95  9]
 [ 4 92]]


In [34]:
#random search cv

In [35]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
model = LogisticRegression()

In [37]:
randomcv = RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,n_iter=10,scoring="accuracy")

In [38]:
randomcv.fit(X_train, y_train)

C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\cemal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the 

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton_cg', 'lbfgs',
                                                   'liblinear', 'sag', 'saga',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [39]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 100}

In [40]:
randomcv.best_score_

np.float64(0.91375)

In [41]:
y_pred = randomcv.predict(X_test)

In [43]:
score = accuracy_score(y_pred, y_test)
print("score: ",score)
print("Classification Report:",classification_report(y_pred, y_test))
print("Confusion Matrix:",confusion_matrix(y_pred, y_test))

score:  0.925
Classification Report:               precision    recall  f1-score   support

           0       0.93      0.92      0.92       100
           1       0.92      0.93      0.93       100

    accuracy                           0.93       200
   macro avg       0.93      0.93      0.92       200
weighted avg       0.93      0.93      0.92       200

Confusion Matrix: [[92  8]
 [ 7 93]]
